#!/bin/bash
#
# Simple more like example wrapper running script
#
#

if [ -z $1 ] ; then
    # Default release
    release=trusty

elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] ; then
    echo "Usage: $0 [release]"
    echo " releases are: iceweasel, trusty, trusty-stable"
    exit 0

else
    if ! [[ "$1" =~ ^(trusty|trusty-stable|iceweasel)$ ]] ; then
        echo "Sorry, unknown release $1"
        exit 1
    else
        release=$1
    fi
fi

echo "Running Firefox ($release)"

if [[ "$OSTYPE" =~ ^[Dd]arwin.* ]] ; then
    echo "MacOs detected"
    if ! open -a xquartz ; then
        echo "Unable to find xquartz app" >&2
        echo "Install with brew" >&2
        exit 1
    fi
    DISP_OPT=${HOSTNAME}:0
    xhost +localhost
else
    DISP_OPT=$DISPLAY
    # Add permissions to xhost
    xhost +local:1000
fi


# Run docker image
docker run -it --rm \
    --user=firefox \
    -e DISPLAY=$DISP_OPT \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    robertvojcik/firefox-icedtea:$release
